## Assignment 2
2.	Classify the email using the binary classification method. Email Spam detection has two states: a) Normal State – Not Spam, b) Abnormal State – Spam. Use K-Nearest Neighbors and Support Vector Machine for classification. Analyze their performance.
Dataset link: The emails.csv dataset on the Kaggle https://www.kaggle.com/datasets/balaka18/email-spam-classification-dataset-csv



In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn import metrics

In [ ]:
df=pd.read_csv('/content/emails.csv')

In [ ]:
df

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  \
0        Email 1    0   0    1    0    0   0    2    0    0  ...       0.0   
1        Email 2    8  13   24    6    6   2  102    1   27  ...       0.0   
2        Email 3    0   0    1    0    0   0    8    0    0  ...       0.0   
3        Email 4    0   5   22    0    5   1   51    2   10  ...       0.0   
4        Email 5    7   6   17    1    5   2   57    0    9  ...       0.0   
...          ...  ...  ..  ...  ...  ...  ..  ...  ...  ...  ...       ...   
1555  Email 1556    1   1    1    0    1   0    8    1    0  ...       0.0   
1556  Email 1557    0   0    1    0    0   0    2    0    0  ...       0.0   
1557  Email 1558    1   1    1    0    1   0    6    0    0  ...       0.0   
1558  Email 1559   14  30   15   14   21  11  260   12    7  ...       0.0   
1559  Email 1560   25  46    9   16    7  19  205   22    1  ...       NaN   

      jay  valued  lay  infrastructure  military  allowing   ff  dry  \
0     0.0     0.0  0.0             0.0       0.0       0.0  0.0  0.0   
1     0.0     0.0  0.0             0.0       0.0       0.0  1.0  0.0   
2     0.0     0.0  0.0             0.0       0.0       0.0  0.0  0.0   
3     0.0     0.0  0.0             0.0       0.0       0.0  0.0  0.0   
4     0.0     0.0  0.0             0.0       0.0       0.0  1.0  0.0   
...   ...     ...  ...             ...       ...       ...  ...  ...   
1555  0.0     0.0  0.0             0.0       0.0       0.0  0.0  0.0   
1556  0.0     0.0  0.0             0.0       0.0       0.0  0.0  0.0   
1557  0.0     0.0  0.0             0.0       0.0       0.0  0.0  0.0   
1558  0.0     0.0  2.0             0.0       0.0       0.0  3.0  0.0   
1559  NaN     NaN  NaN             NaN       NaN       NaN  NaN  NaN   

      Prediction  
0            0.0  
1            0.0  
2            0.0  
3            0.0  
4            0.0  
...          ...  
1555         0.0  
1556         1.0  
1557         0.0  
1558         1.0  
1559         NaN  

[1560 rows x 3002 columns]

In [ ]:
df.head()

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  jay  \
0   Email 1    0   0    1    0    0   0    2    0    0  ...       0.0  0.0   
1   Email 2    8  13   24    6    6   2  102    1   27  ...       0.0  0.0   
2   Email 3    0   0    1    0    0   0    8    0    0  ...       0.0  0.0   
3   Email 4    0   5   22    0    5   1   51    2   10  ...       0.0  0.0   
4   Email 5    7   6   17    1    5   2   57    0    9  ...       0.0  0.0   

   valued  lay  infrastructure  military  allowing   ff  dry  Prediction  
0     0.0  0.0             0.0       0.0       0.0  0.0  0.0         0.0  
1     0.0  0.0             0.0       0.0       0.0  1.0  0.0         0.0  
2     0.0  0.0             0.0       0.0       0.0  0.0  0.0         0.0  
3     0.0  0.0             0.0       0.0       0.0  0.0  0.0         0.0  
4     0.0  0.0             0.0       0.0       0.0  1.0  0.0         0.0  

[5 rows x 3002 columns]

In [ ]:
df.info

<bound method DataFrame.info of        Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  \
0        Email 1    0   0    1    0    0   0    2    0    0  ...       0.0   
1        Email 2    8  13   24    6    6   2  102    1   27  ...       0.0   
2        Email 3    0   0    1    0    0   0    8    0    0  ...       0.0   
3        Email 4    0   5   22    0    5   1   51    2   10  ...       0.0   
4        Email 5    7   6   17    1    5   2   57    0    9  ...       0.0   
...          ...  ...  ..  ...  ...  ...  ..  ...  ...  ...  ...       ...   
1555  Email 1556    1   1    1    0    1   0    8    1    0  ...       0.0   
1556  Email 1557    0   0    1    0    0   0    2    0    0  ...       0.0   
1557  Email 1558    1   1    1    0    1   0    6    0    0  ...       0.0   
1558  Email 1559   14  30   15   14   21  11  260   12    7  ...       0.0   
1559  Email 1560   25  46    9   16    7  19  205   22    1  ...       NaN   

      jay  valued  lay  infrast

In [ ]:
df.shape

(1560, 3002)

In [ ]:
df.columns

Index(['Email No.', 'the', 'to', 'ect', 'and', 'for', 'of', 'a', 'you', 'hou',
       ...
       'connevey', 'jay', 'valued', 'lay', 'infrastructure', 'military',
       'allowing', 'ff', 'dry', 'Prediction'],
      dtype='object', length=3002)

In [ ]:
df.isnull().sum()

Email No.     0
the           0
to            0
ect           0
and           0
             ..
military      1
allowing      1
ff            1
dry           1
Prediction    1
Length: 3002, dtype: int64

In [ ]:
df.dropna(inplace = True)

In [ ]:
df.drop(['Email No.'],axis=1,inplace=True)
X = df.drop(['Prediction'],axis = 1)
y = df['Prediction']

In [ ]:
df

the  to  ect  and  for  of    a  you  hou  in  ...  connevey  jay  \
0       0   0    1    0    0   0    2    0    0   0  ...       0.0  0.0   
1       8  13   24    6    6   2  102    1   27  18  ...       0.0  0.0   
2       0   0    1    0    0   0    8    0    0   4  ...       0.0  0.0   
3       0   5   22    0    5   1   51    2   10   1  ...       0.0  0.0   
4       7   6   17    1    5   2   57    0    9   3  ...       0.0  0.0   
...   ...  ..  ...  ...  ...  ..  ...  ...  ...  ..  ...       ...  ...   
1554    1   2    1    0    1   0    6    1    0   0  ...       0.0  0.0   
1555    1   1    1    0    1   0    8    1    0   0  ...       0.0  0.0   
1556    0   0    1    0    0   0    2    0    0   1  ...       0.0  0.0   
1557    1   1    1    0    1   0    6    0    0   0  ...       0.0  0.0   
1558   14  30   15   14   21  11  260   12    7  49  ...       0.0  0.0   

      valued  lay  infrastructure  military  allowing   ff  dry  Prediction  
0        0.0  0.0             0.0       0.0       0.0  0.0  0.0         0.0  
1        0.0  0.0             0.0       0.0       0.0  1.0  0.0         0.0  
2        0.0  0.0             0.0       0.0       0.0  0.0  0.0         0.0  
3        0.0  0.0             0.0       0.0       0.0  0.0  0.0         0.0  
4        0.0  0.0             0.0       0.0       0.0  1.0  0.0         0.0  
...      ...  ...             ...       ...       ...  ...  ...         ...  
1554     0.0  0.0             0.0       0.0       0.0  0.0  0.0         0.0  
1555     0.0  0.0             0.0       0.0       0.0  0.0  0.0         0.0  
1556     0.0  0.0             0.0       0.0       0.0  0.0  0.0         1.0  
1557     0.0  0.0             0.0       0.0       0.0  0.0  0.0         0.0  
1558     0.0  2.0             0.0       0.0       0.0  3.0  0.0         1.0  

[1559 rows x 3001 columns]

In [ ]:
from sklearn.preprocessing import scale
X = scale(X)
# split into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

In [ ]:
X

array([[-0.57067245, -0.66372063, -0.31583176, ..., -0.07181896,
        -0.2849181 , -0.09856483],
       [ 0.10724228,  0.69283705,  1.03011301, ..., -0.07181896,
         0.00276799, -0.09856483],
       [-0.57067245, -0.66372063, -0.31583176, ..., -0.07181896,
        -0.2849181 , -0.09856483],
       ...,
       [-0.57067245, -0.66372063, -0.31583176, ..., -0.07181896,
        -0.2849181 , -0.09856483],
       [-0.48593311, -0.55937004, -0.31583176, ..., -0.07181896,
        -0.2849181 , -0.09856483],
       [ 0.61567833,  2.4667971 ,  0.50343897, ..., -0.07181896,
         0.57814015, -0.09856483]])

In [ ]:
X_train

array([[ 0.02250294,  0.48413587, -0.31583176, ..., -0.07181896,
         0.86582623, -0.09856483],
       [-0.0622364 ,  0.1710841 , -0.25731242, ..., -0.07181896,
        -0.2849181 , -0.09856483],
       [-0.57067245, -0.35066886, -0.25731242, ..., -0.07181896,
        -0.2849181 , -0.09856483],
       ...,
       [-0.31645442, -0.66372063, -0.31583176, ..., -0.07181896,
        -0.2849181 , -0.09856483],
       [-0.57067245, -0.66372063, -0.31583176, ..., -0.07181896,
        -0.2849181 , -0.09856483],
       [ 0.10724228, -0.55937004,  0.15232295, ..., -0.07181896,
        -0.2849181 , -0.09856483]])

In [ ]:
X_test

array([[-2.31715082e-01, -5.59370037e-01, -3.15831757e-01, ...,
        -7.18189571e-02, -2.84918096e-01, -9.85648310e-02],
       [-5.70672447e-01, -5.59370037e-01, -1.40273743e-01, ...,
        -7.18189571e-02,  2.76798668e-03, -9.85648310e-02],
       [-4.85933106e-01, -4.55019446e-01,  3.52842704e-02, ...,
        -7.18189571e-02, -2.84918096e-01, -9.85648310e-02],
       ...,
       [-2.31715082e-01, -5.59370037e-01, -2.57312419e-01, ...,
        -7.18189571e-02, -2.84918096e-01, -9.85648310e-02],
       [ 4.51368803e+00,  3.30160183e+00,  3.52842704e-02, ...,
        -7.18189571e-02,  8.65826234e-01, -9.85648310e-02],
       [-3.16454423e-01, -2.46318265e-01, -3.15831757e-01, ...,
        -7.18189571e-02, -2.84918096e-01, -9.85648310e-02]])

In [ ]:
y_train

598     0.0
661     0.0
312     0.0
1225    0.0
1131    0.0
       ... 
1130    0.0
1294    1.0
860     1.0
1459    0.0
1126    0.0
Name: Prediction, Length: 1091, dtype: float64

In [ ]:
y_test

1524    0.0
1483    0.0
354     0.0
668     0.0
1422    1.0
       ... 
398     0.0
423     1.0
370     0.0
54      0.0
1281    1.0
Name: Prediction, Length: 468, dtype: float64

In [ ]:
X_train.shape

(1091, 3000)

In [ ]:
X_test.shape

(468, 3000)

In [ ]:
y_train.shape

(1091,)

In [ ]:
y_test.shape

(468,)

##KNN classifier

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)

knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

In [ ]:
print("Prediction",y_pred)   # 1 for spam 0 for not spam

Prediction [1. 0. 1. 0. 1. 0. 1. 1. 1. 0. 0. 1. 0. 0. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0.
 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 0. 1. 1. 0. 0. 0. 0.
 1. 1. 1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 1. 0. 1. 1. 1. 0.
 1. 0. 1. 0. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1.
 0. 0. 0. 1. 1. 1. 1. 0. 1. 0. 1. 1. 0. 1. 1. 0. 1. 0. 0. 1. 0. 1. 0. 0.
 1. 0. 0. 0. 1. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0.
 1. 0. 1. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0.
 1. 0. 1. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0.
 0. 0. 1. 1. 1. 1. 0. 0. 0. 1. 1. 0. 0. 1. 1. 1. 0. 1. 0. 1. 0. 1. 1. 0.
 1. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 1. 1.
 1. 1. 0. 1. 0. 1. 1. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.
 1. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 1. 0.
 0. 1. 1. 1. 0. 0. 1. 0. 1. 1. 0. 0. 1. 

In [ ]:
print("KNN accuracy = ",metrics.accuracy_score(y_test,y_pred))

KNN accuracy =  0.7564102564102564


In [ ]:
print("Confusion matrix",metrics.confusion_matrix(y_test,y_pred))

Confusion matrix [[228 106]
 [  8 126]]


## SVM classifier

In [ ]:
# cost C = 1
model = SVC()   # C is an offset value to account for some mis-classification of data that can happen.

# fit
model.fit(X_train, y_train)

# predict
y_pred = model.predict(X_test)

In [ ]:
print("SVM accuracy = ",metrics.accuracy_score(y_test,y_pred))

SVM accuracy =  0.8888888888888888


In [ ]:
metrics.confusion_matrix(y_true=y_test, y_pred=y_pred)

array([[334,   0],
       [ 52,  82]])